### ISSUE TITLE
use my own data

### ISSUE THREAD

**Issue by nikipi** [PAIR-code/what-if-tool#114]
Hi James and Team,

Is it possible to use my own data but still have the same front end?

**Comment by jameswex** [comment]
You can use your own data with WIT either through using it in notebooks (Jupyter or  Colab), or in TensorBoard.  Here are startup guides with more details on those two options: https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/ and https://pair-code.github.io/what-if-tool/learn/tutorials/tensorboard/

https://pair-code.github.io/what-if-tool/explore/#notebook shows colab notebooks with many examples of using your own data with WIT in notebooks.

**Comment by vach-aiml** [comment]
Does the WIT tool accept only tf.example as data? Is it compulsory to convert my Images dataset into tf.Example protos?

**Comment by jameswex** [comment]
When using the WIT tool in TensorBoard, then the tool does expect a TFRecord of tf.Example protos, but when using it in notebooks like Jupyter or Colab, then other options are available as per https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/

But if your input data are images, that has only been tested with tf.Example protos (with an "image/encoded" feature that contains the base 64 encoded string for an image). See https://colab.sandbox.google.com/github/PAIR-code/what-if-tool/blob/master/WIT_Smile_Detector.ipynb for an example usage with images, including converting them to tf.Examples.
