### ISSUE TITLE
Can we use the what-if-tool off-line?

### ISSUE THREAD

**Issue by AndreiStoian-education** [PAIR-code/what-if-tool#115]
Good morning, Thank you so much for this amazing piece of work. When I saw the presentation I immediately thought of our leaders and how might they benefit from the understanding that this process brings. Due to the nature of the data that we are working with here at the Ministry of Education we would never be able to use this tool effectively because of the breach in confidentiality. Is there a way to use this tool on the local machine and have it display the results just as it would have done in the cloud? 
Thank you again for your time and suppor.
Best Regards,

Andrei.

**Comment by jameswex** [comment]
The What-If Tool can be run on your own machine in one of two ways: either in an instance of Tensorboard that you run locally on your machine, or through a jupyter notebook where you run the kernel locally on your machine. In both cases, there is no interaction with the cloud.

Tutorials for both ways of setting up WIT can be found at https://pair-code.github.io/what-if-tool/learn/tutorials/tensorboard/ and https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/
