### ISSUE TITLE
Tensorboard Walkthrough not accessible

### ISSUE THREAD

**Issue by florence27** [PAIR-code/what-if-tool#124]
Hey everyone, when trying to open the [link](https://pair-code.github.io/what-if-tool/learn/tutorials/walkthrough/tensorboard) to the Tensorboard Walkthrough on the [WhatIf-Tool Homepage](https://pair-code.github.io/what-if-tool/learn/tutorials/walkthrough/) I get a 404-File not found error. It would be nice to have a TB walkthrough for WIT though, since I'm kind of stuck with my own code right now. Any help with this is appreciated!
Thanks & Cheers!

**Comment by jameswex** [comment]
Thanks for the bug report! Looks like a bad link in that article. The correct link is https://pair-code.github.io/what-if-tool/learn/tutorials/tensorboard/  Check that page out for TensorBoard-specific setup instructions.

We'll fix the website and use this issue to track that.
