### ISSUE TITLE
Support for TF Datasets and Keras Preprocessing

### ISSUE THREAD

**Issue by coryroyce** [PAIR-code/what-if-tool#129]
I'm trying to use the What-If Tool on my project but it seems like [TensorFlow Datasets](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) are not supported. This seems like one of the more common data formats for training models and I wanted to know if Datasets are supported or not. If I missed the documentation or if anyone has a link to a sample Colab notebook that uses Datasets with the What-If Tool, that would be very helpful.

A related question is the support for Pre-processing in TF/Keras. Some of the preprocessing features are experimental, but getting the dataset and preprocessing into the What-If Tool has been challenging for me.

Here is an example [notebook](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/preprocessing_layers.ipynb) that uses [Datasets and Preprocessing](https://www.tensorflow.org/tutorials/structured_data/preprocessing_layers) that I would live help getting the What-If Tool working on.

Thanks in advanced for any feedback or help.

**Comment by jameswex** [comment]
Thanks for reaching out. You're right that tf.Datasets aren't natively supported at this point. I did take that example notebook and add WIT to it to see what was necessary.  Here's what I had to do:

```
!pip install witwidget

def custom_predict(records):
  # Convert list of dicts to Dataframe and then to tf.Dataset, without shuffling.
  records_ds = df_to_dataset(pd.DataFrame(records), shuffle=False)

  # Call predict and sigmoid to get positive class score, just like is done earlier in the notebook
  positive_scores = tf.nn.sigmoid(model.predict(records_ds).squeeze()).numpy()
  
  # WIT custom predict functions should return [neg score, pos score] for each
  # binary classification prediction.
  results = [[1 - score, score] for score in positive_scores] 
  return results

from witwidget.notebook.visualization import WitConfigBuilder
from witwidget.notebook.visualization import WitWidget

# Provide list of dictionaries to WIT, as it can accept that dataset format.
test_records = test.to_dict(orient="records")
config_builder = WitConfigBuilder(test_records).set_custom_predict_fn(custom_predict)
a = WitWidget(config_builder)
```

**Comment by coryroyce** [comment]
Thank you @jameswex this was really helpful and I was able to apply it to my model.

One follow up question, my actual model it is a Regression model that outputs a float value between 0 and 400. Is there a setting change to the WIT that is better suited for showing the influence of input features on regression models rather than binary clarification metrics?

**Comment by jameswex** [comment]
No problem. For regression models, have the custom_predict fn return a single score per record instead of the list of two class scores, and call ".set_model_type('regression')" on the WitConfigBuilder object.

**Comment by coryroyce** [comment]
Really appreciate the help.
