### ISSUE TITLE
Question: Explainable AI for Features for Regression Models

### ISSUE THREAD

**Issue by coryroyce** [PAIR-code/what-if-tool#130]
Is there a setting or simple way to get global feature information (like Shapely Values) for regression models (Keras layers or sequential models)? 

I saw the [Explainable AI](https://cloud.google.com/ai-platform/prediction/docs/ai-explanations/overview) tool set for Google Cloud and though that similar information may already be in the WIT tool since it can show how much the predicted value changes based on changing individual data point features, but the Global Feature information make it much easier to understand what is influencing the model.

**Comment by jameswex** [comment]
You can use the partial dependence plot feature to create global partial dependence plots to view the average effect of each feature on prediction. To do so, either click on the "partial dependence plots" button when no datapoint is selected, or flip the switch in the top-right of the partial dependence plots area to "global".

This will show a single chart for each feature of the average affect of each feature value on prediction.  You can then click the "sort by variation" button to have the features in this section sorted by how much variation in predictions happens (on average across the dataset) as that feature is changed.

Additionally, if you use a custom predict function, and have the custom predict function return individual feature attribution scores along with each prediction, then you can visualize those results in the tool as well. There is some information about this in the "custom prediction function" section of the https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/ tutorial. The https://colab.sandbox.google.com/github/pair-code/what-if-tool/blob/master/WIT_COMPAS_with_SHAP.ipynb notebook shows this in action. It creates a keras model, and uses the shap library to get shapley scores for each prediction in the custom prediction function.

By doing so, now you can see feature importance for any selected datapoint in the datapoint editor, and also if you go to the "Performance" tab you can see a table of average feature attributions across the dataset (or a slice of the dataset), sorted by strength of attribution.

We plan to put out a new tutorial on our https://pair-code.github.io/what-if-tool/learn/ page with more details on this capability in the coming weeks.

**Comment by coryroyce** [comment]
Thanks again for the great answer.
