### ISSUE TITLE
Clarity on Counterfactual Reasoning

### ISSUE THREAD

**Issue by drishyamlabs** [PAIR-code/what-if-tool#138]
Hi,

Thanks a lot for the great tool. Just could not understand how counterfactuals are computed for categorical variables.

As per section 4.2.2 of the paper:
• Categorical features: Data points with the same value have a
distance of 0, and other distances are set to the probability that
any two examples across the entire dataset would share the same
value for that feature.

Not able to understand what this means. Any elaboration will be appreciated.

Thanks in advance.

**Comment by jameswex** [comment]
Thanks for reaching out.

Imagine a categorical feature with two values: A or B.

If 50% of all examples have value A and 50% have value B: When computing distance between two datapoints, the feature-wise distance for this feature would be 0 if both datapoints have the same value. But if one datapoint has value A and one has value B, then its distance for this feature would be 0.5 * 0.5 + 0.5 * 0.5 = 0.5

If 20% of all examples have value A and 80% have value B: If two datapoints have different values, the distance for this feature would be 0.2 * 0.2 + 0.8 * 0.8 = 0.68.

**Comment by xiaohk** [comment]
Hello @jameswex, I am also a little bit confused about `the probability that any two examples across the entire dataset would share the same value for that feature`.

For example, say we have three values A, B, and C for a categorical variable with frequency 0.2, 0.3, and 0.5.

Does it imply the following?

Point 1 has value A; Point 2 has value A => distance = 0
Point 1 has value A; Point 2 has value B => distance = 0.2 * 0.2 + 0.3 * 0.3 + 0.5 * 0.5 = 0.38
Point 1 has value A; Point 2 has value C => distance = 0.2 * 0.2 + 0.3 * 0.3 + 0.5 * 0.5 = 0.38

**Comment by jameswex** [comment]
Yes, that is correct @xiaohk

**Comment by xiaohk** [comment]
Got it, thanks! @jameswex
