### ISSUE TITLE
Jupyter WitWidget can get into bad state with identical predictions

### ISSUE THREAD

**Issue by jameswex** [PAIR-code/what-if-tool#139]
If you edit a datapoint and press Predict, the result for that prediction is updated.
If you then edit that same datapoint again and press Predict, AND the model returns the same exact prediction score for that datapoint as the previous prediction, then the What-If Tool will get into a bad state where it doesn't update the prediction correctly.

This only happens in Jupyter.

It is due to the use of Traitlets for the new inferences. And in this case the inferences traitlet is updated to the same value as before, so it doesn't cause a javascript update. 

A solution would be to add a counter to the inference results traitlet to ensure every inference is different.

**Comment by jameswex** [comment]
cc @tolga-b and his work in #127

**Comment by jameswex** [comment]
Fixing in #144

**Comment by tolga-b** [comment]
@jameswex I think this is fixed, closing it.
