### ISSUE TITLE
Clarifying how selection updates UI for counterfactuals

### ISSUE THREAD

**Issue by kevinrobinson** [PAIR-code/what-if-tool#14]
hi, thanks for sharing all your awesome work! 👍 

I was exploring the UCI dataset on the web demo while reading the paper and it looks to me like there might be a bug in how the UI state updates to color which elements of the counterfactual are different.  Alternately, it might be I'm just misunderstanding the UX :)

I'm expecting that when I look at a data point, the attributes of the counterfactual that are different will be shown in green, like the "occupation" and "relationship" values here:

![image](https://user-images.githubusercontent.com/1056957/61740572-f6292980-ad5c-11e9-9765-5cc4288c5f4a.png)

To reproduce:

1. Bin the x-axis by occupation:
<img width="731" alt="Screen Shot 2019-07-23 at 3 18 08 PM" src="https://user-images.githubusercontent.com/1056957/61740641-22dd4100-ad5d-11e9-9b44-0f1b2d8622ac.png">

2. Zoom into "Transport-moving" at the bottom and click on the lowest ">50k" data point, colored red and highlighted here:

![image](https://user-images.githubusercontent.com/1056957/61740701-4607f080-ad5d-11e9-932f-ca4f53ec506c.png)

3. Enable showing counterfactuals
Notice that "occupation" and "relationship" are highlighted in green, which is in line with what I'd expect since they're different:
![image](https://user-images.githubusercontent.com/1056957/61740731-5ae48400-ad5d-11e9-9155-6530d29a2e64.png)

4. Click on the highest "<50k" data point, colored blue and highlighted here:
![image](https://user-images.githubusercontent.com/1056957/61741176-4d7bc980-ad5e-11e9-9da2-29d0016cc27a.png)

5. Check out the counterfactual
It looks like some attributes that are the same are highlighted in green, which is not what I would expect.  In this screenshot, I'd expect "occupation" to be green but "relationship" to be standard black text.
![image](https://user-images.githubusercontent.com/1056957/61740817-8f584000-ad5d-11e9-9a2a-71e4f67f0716.png)

Note that the highlighting behavior is different if you clear the selection, and then click on the data point in step 4 directly.  That shows these attributes highlighted, as I'd expected:

![image](https://user-images.githubusercontent.com/1056957/61741021-fd046c00-ad5d-11e9-8a0f-b1d2f5721ad9.png)

So this might be a UX misunderstanding, and maybe I'm not understanding how the counterfactual computation is supposed to interact with the selection.  But since the behavior is different depending on the order of doing this, I suspect it's a UI bug with updating in response to state changes.  I poked around a bit and seemed like maybe [around here](https://github.com/tensorflow/tensorboard/blob/fa56d0cc787260a4778f6aefc757125589e6ed95/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/tf-interactive-inference-dashboard.html#L4654) is where the syncing between selection interactions, changing the values, and rendering the color [here](https://github.com/tensorflow/tensorboard/blob/223073b9fe085d092a407bb3466c9f82733cfe0d/tensorboard/components/vz_example_viewer/vz-example-viewer.html#L499).

Thanks!  Let me know if there's anything else I can provide that's helpful for debugging.

**Comment by jameswex** [comment]
Thanks so much for the detailed bug report! Looks like a UI bug as you suspected. We will take a look.

**Comment by jameswex** [comment]
Forgot to close this bug after it was fixed in a code change months ago when the code was still in the TensorBoard repo. Thanks again for the report!
