### ISSUE TITLE
Does WIT support Pytorch?

### ISSUE THREAD

**Issue by srkm009** [PAIR-code/what-if-tool#143]
Hello, I have used WIT within TF & TFboard and it is fantastic! I have a project where I want to use WIT within pytorch & TFboard/ WIT. I saw a blog post saying WIT is not exclusive to TF but i could not find any documentation regarding Pytorch support. Thanks.

**Comment by jameswex** [comment]
Thanks for reaching out. To use WIT with a PyTorch model, you should use the "custom prediction function" capability to provide your own python function that runs model prediction. You can use a custom prediction function whether you use WIT inside TensorBoard or inside of notebooks (like colab or jupyter).

For custom prediction function usage, see the tutorials https://pair-code.github.io/what-if-tool/learn/tutorials/tensorboard/ and https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/

I don't have any demo examples that use PyTorch models, but they should look similar to the existing demo notebooks linked in those tutorials, but with PyTorch model prediction code inside the custom prediction function.

**Comment by srkm009** [comment]
Thanks for the pointers. Are more examples/ notebooks planned in the roadmap for usage with other frameworks? I wanted to understand how easy it would be for other developers & data scientists to adopt this tool.

**Comment by jameswex** [comment]
What frameworks would you like to see example WIT notebooks of, added to https://pair-code.github.io/what-if-tool/explore ? I think we currently have TF and Keras examples, and we also have sklearn and xgboost (but those two framework uses are through Cloud AI Platform deployments to serve the predictions from the models).

I think it should be easy for us to create and share a simple UCI census example of WIT with other frameworks, such as PyTorch.

**Comment by srkm009** [comment]
Yes, pytorch would be a good place to have more documentation for native/ standalone deployments. Yes, documentation for TF/ Keras is excellent and i did start there too. Thanks. 
P.S. Sorry about the delayed response as my internet is pretty unstable during travel

**Comment by jameswex** [comment]
Here is a colab notebook that trains a PyTorch binary classifier and runs WIT with it.

[WIT_with_a_PyTorch_Model_UCI_Census_Binary_Classification.ipynb.zip](https://github.com/PAIR-code/what-if-tool/files/5755432/WIT_with_a_PyTorch_Model_UCI_Census_Binary_Classification.ipynb.zip)

**Comment by srkm009** [comment]
Cool! Thanks for getting something ready so fast. I think i understand the custom predictor better now. 
While running the notebook, it exist without any output as such (Was expecting the WIT notebook widget to come up): 
![image](https://user-images.githubusercontent.com/1845232/103919201-12b35000-5110-11eb-82ee-b86ee5a5b3d0.png)

Is there any more lines to be added to make it come up?

**Comment by jameswex** [comment]
If you are using it in a Jupyter notebook (and not colab), I think you'll need to add a wv.render() call as well. Sorry I missed that.

**Comment by srkm009** [comment]
Yes, I figured that immediately after posting the comment ;) Thanks!
