### ISSUE TITLE
It seems WIF doesn't support multiple inputs with predict API

### ISSUE THREAD

**Issue by itechbear** [PAIR-code/what-if-tool#151]
Hi dev team,

I just tried WIF on tensorboard, but couldn't get inferences to work with *multiple-inputs*. I hope I can get some help here.

### Background about the model

I developed a TF model and deployed it using TF serving predict API, with both HTTP and GRPC ports open. It can be confirmed to be working with following command
```sh
$ curl -d '{"inputs": {"FEATURE_1": [[1]], "FEATURE_2":[[1]]}}' -X POST http://SOME_IPV4_ADDRESS:SOME_HTTP_PORT/v1/models/alpha:predict 
{
    "outputs": [
        [
            0.999730885
        ]
    ]
}
``` 
and the following is the metadata of the model
```json
{
  "model_spec": {
    "name": "alpha",
    "signature_name": "",
    "version": "20210228015535"
  },
  "metadata": {
    "signature_def": {
      "signature_def": {
        "serving_default": {
          "inputs": {
            "FEATURE_1": {
              "dtype": "DT_DOUBLE",
              "tensor_shape": {
                "dim": [
                  {
                    "size": "-1",
                    "name": ""
                  },
                  {
                    "size": "1",
                    "name": ""
                  }
                ],
                "unknown_rank": false
              },
              "name": "serving_default_QUERY_LENGTH:0"
            },
            "FEATURE_2": {
              "dtype": "DT_DOUBLE",
              "tensor_shape": {
                "dim": [
                  {
                    "size": "-1",
                    "name": ""
                  },
                  {
                    "size": "1",
                    "name": ""
                  }
                ],
                "unknown_rank": false
              },
              "name": "serving_default_QUERY_USER_INFO_MATCHED_RATIO:0"
            }
          },
          "outputs": {
            "output": {
              "dtype": "DT_FLOAT",
              "tensor_shape": {
                "dim": [
                  {
                    "size": "-1",
                    "name": ""
                  },
                  {
                    "size": "1",
                    "name": ""
                  }
                ],
                "unknown_rank": false
              },
              "name": "StatefulPartitionedCall:0"
            }
          },
          "method_name": "tensorflow/serving/predict"
        },
        "__saved_model_init_op": {
          "inputs": {},
          "outputs": {
            "__saved_model_init_op": {
              "dtype": "DT_INVALID",
              "tensor_shape": {
                "dim": [],
                "unknown_rank": true
              },
              "name": "NoOp"
            }
          },
          "method_name": ""
        }
      }
    }
  }
}
```

### Problems
When I tried to setup WIF, I filled the "input tensor name" field with  "FEATURE_1,FEATURE_2" (without quotes), but WIF always complained with 500 error. Log messages say something like
```
debug_error_string = "{"created":"@1614673818.179555962","description":"Error received from peer ipv4:SOME_IPV4_ADDRESS:SOME_GRPC_PORT","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"input size does not match signature: 1!=2 len({FEATURE_1, FEATURE_2}) != len({FEATURE_1, FEATURE_2}). Sent extra ...
```

### Current finding
I tried different tensor names, but got no luck. I then read the source code of WIF, and found this line: [platform_utils.py#L230](https://github.com/PAIR-code/what-if-tool/blob/697c0982f873c0b56d1cc01159f5fba2a87fc464/utils/platform_utils.py#L230) .
```python
      request.inputs[serving_bundle.predict_input_tensor].CopyFrom(
        tf.compat.v1.make_tensor_proto(
          values=[ex.SerializeToString() for ex in batch_examples],
          dtype=types_pb2.DT_STRING))
```
**It seems that it expects `input_tensor` to be a string** instead of a list so *multiple-inputs* are not supported at all. However, I'm not so sure. Can you please help check? Thank you!

**Comment by jameswex** [comment]
Thanks for reaching out and for the detailed bug report! You are correct in that WIT's logic for sending requests to models served by the TF serving package requires that inputs be a single string that is a serialized tf.Example proto.

The easiest path forward for you, assuming you want to keep your model as having the same API as it does now, would be to use the "custom prediction function" capability of WIT to provide your own python function that takes in the inputs to be predicted, and calls the model itself and returns the model predictions in the correct form. This python function could simply run the same curl command you showed to work at the top of the bug. 

Details on how to set up a custom prediction function can be found in https://pair-code.github.io/what-if-tool/learn/tutorials/tensorboard/ (for when using WIT inside TensorBoard) and https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/ (for when using WIT inside of colab or jupyter notebooks).

Let me know if you need any help getting your custom prediction function to work.

**Comment by itechbear** [comment]
Thank you James! I'll give custom prediction function a try.

**Comment by itechbear** [comment]
I've successfully get it to work using `custom prediction function`. 

For anyone who comes here, there's another option to make it work by hacking the source code. You can refer to [Tensorboard what if tool](https://zhuanlan.zhihu.com/p/158461844). Though I didn't try myself.
