### ISSUE TITLE
Issue with ML for Business professional training

### ISSUE THREAD

**Issue by FANMixco** [PAIR-code/what-if-tool#16]
There is one point that has been gone that is: Group unaware and in the training they suggest to click. What happened? Thanks.

**Comment by jameswex** [comment]
In the latest version of the What-If Tool, "group unaware" has been renamed to "single threshold" to be more clear about what it does.

**Comment by jameswex** [comment]
Also, do you have a link to that training? Thank you.

**Comment by FANMixco** [comment]
Hi @jameswex , the course is here:
coursera.org/learn/machine-learning-business-professionals

And it's from Google Cloud.

**Comment by jameswex** [comment]
Thanks for bringing this up. I'll reach out to them. In the meantime, when they mention "group unaware", you can use the "single threshold" button.
