### ISSUE TITLE
WIT works on Multi-Class Classification ?

### ISSUE THREAD

**Issue by okanbuyuktepe** [PAIR-code/what-if-tool#168]
Hi, 
Firstly many thanks to who designed this amazing tool! I have a dataset includes seven label features. I loaded the test datapoints into WIT but, I cant see seven different ROC & PR curves in Performance and Fairness tab of WIT, just one is displayed. My model gives such prediction results : [[8.5288650e-01 1.4615927e-05 1.4662699e-01 4.5985775e-04 1.0260558e-07
  4.4352169e-06 7.3788956e-06]]. 

Could you please help ?

**Comment by jameswex** [comment]
How you are setting up your WIT? Is it inside of a notebook or thought TensorBoard? Either way, you will need to specify that you are using it for a multi-class problem (as opposed to binary classification). In notebook mode, call set_multi_class(True) on WitConfigBuilder (https://pair-code.github.io/what-if-tool/learn/tutorials/notebooks/ for more details). In TensorBoard, there is a checkbox in the WIT setup UI.

**Comment by okanbuyuktepe** [comment]
It worked! Thank you.
After calling call set_multi_class(True), the Performance tab is displayed as in figure. However, the Fairness tab is gone. Is it expected behaviour ?

![Capture](https://user-images.githubusercontent.com/48437747/128071231-a98aa12c-6339-496d-95d1-3e89c7850ec1.PNG)

**Comment by jameswex** [comment]
Glad to hear it worked for you. Yes, the fairness-related logic in WIT only applies to binary classifiers.

**Comment by okanbuyuktepe** [comment]
I really appreciate all the help you gave me. 
Have a nice day :)
