### ISSUE TITLE
Error displaying widget  on Kubeflow 1.3.x  JuypterLab

### ISSUE THREAD

**Issue by mkhaas** [PAIR-code/what-if-tool#178]
Greetings, 

I am trying to  run  https://colab.research.google.com/github/pair-code/what-if-tool/blob/master/What_If_Tool_Notebook_Usage.ipynb  on  Kubeflow on the latest kubeflow JuypterLab  notebook server.

I tried the following commands on my  terminal
(base) jovyan@t2-0:~$ 
    1  pip install witwidget
    2  jupyter labextension install wit-widget
    3  jupyter labextension install @jupyter-widgets/jupyterlab-manager

When I run the What-if-notebook I get the following Error " Error displaying widget".

Any recommendations on where I should look or how to fix it?  

Thank you

**Comment by jameswex** [comment]
What version of jupyterlab does that use? It's possible that WIT doesn't work correctly in jupyterlab 3 as we haven't tested that newest major version.

See https://github.com/PAIR-code/what-if-tool/issues/164 for other information.

**Comment by mkhaas** [comment]
Thank you @jameswex jupyterlab==3.0.16  and here are the other packages  I will follow  #164 for updates

absl-py==0.11.0
adal==1.2.7
anyio==3.1.0
argon2-cffi==20.1.0
astunparse==1.6.3
async-generator==1.10
attrs==21.2.0
avro==1.10.2
azure-common==1.1.27
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
Babel==2.9.1
backcall==0.2.0
bleach==3.3.0
bokeh==2.3.2
brotlipy==0.7.0
cachetools==4.2.2
certifi==2021.5.30
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1613413861439/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1610093490430/work
click==7.1.2
cloudevents==1.2.0
cloudpickle==1.6.0
colorama==0.4.4
conda==4.10.1
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1618231394280/work
configparser==5.0.2
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1616851476134/work
cycler==0.10.0
decorator==4.4.2
defusedxml==0.7.1
Deprecated==1.2.12
deprecation==2.1.0
dill==0.3.4
docstring-parser==0.8.1
entrypoints==0.3
fire==0.4.0
flatbuffers==1.12
gast==0.4.0
gitdb==4.0.7
GitPython==3.1.18
google-api-core==1.30.0
google-api-python-client==1.12.8
google-auth==1.31.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.4
google-cloud-core==1.7.0
google-cloud-storage==1.39.0
google-crc32c==1.1.2
google-pasta==0.2.0
google-resumable-media==1.3.1
googleapis-common-protos==1.53.0
grpcio==1.34.1
h5py==3.1.0
httplib2==0.19.1
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1593328102638/work
imageio==2.9.0
ipykernel==5.5.5
ipympl==0.7.0
ipython==7.24.1
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
Jinja2==3.0.1
joblib==1.0.1
json5==0.9.5
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyter-server==1.8.0
jupyter-server-mathjax==0.2.3
jupyterlab==3.0.16
jupyterlab-git==0.30.1
jupyterlab-pygments==0.1.2
jupyterlab-server==2.6.0
jupyterlab-widgets==1.0.0
Keras==2.4.3
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
kfp==1.6.3
kfp-pipeline-spec==0.1.8
kfp-server-api==1.6.0
kfserving==0.5.1
kiwisolver==1.3.1
kubernetes==12.0.1
Markdown==3.3.4
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
minio==6.0.2
mistune==0.8.4
nbclassic==0.3.1
nbclient==0.5.3
nbconvert==6.0.7
nbdime==3.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
networkx==2.5.1
notebook==6.4.0
numpy==1.19.5
oauth2client==4.1.3
oauthlib==3.1.1
opt-einsum==3.3.0
packaging==20.9
pandas==1.2.4
pandocfilters==1.4.3
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.2.0
prometheus-client==0.11.0
prompt-toolkit==3.0.18
protobuf==3.17.3
ptyprocess==0.7.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycosat @ file:///home/conda/feedstock_root/build_artifacts/pycosat_1610094800877/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1593275161868/work
Pygments==2.9.0
PyJWT==2.1.0
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1608055815057/work
pyparsing==2.4.7
pyrsistent==0.17.3
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1610291447907/work
python-dateutil==2.8.1
pytz==2021.1
PyWavelets==1.1.1
PyYAML==5.4.1
pyzmq==22.1.0
qtconsole==5.1.1
QtPy==1.11.0
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1608156231189/work
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rsa==4.7.2
ruamel-yaml-conda @ file:///home/conda/feedstock_root/build_artifacts/ruamel_yaml_1611943339799/work
scikit-image==0.18.1
scikit-learn==0.24.2
scipy==1.7.0
seaborn==0.11.1
Send2Trash==1.5.0
six==1.15.0
smmap==4.0.0
sniffio==1.2.0
strip-hints==0.1.9
table-logger==0.3.6
tabulate==0.8.9
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0
tensorflow-estimator==2.5.0
termcolor==1.1.0
terminado==0.10.0
testpath==0.5.0
threadpoolctl==2.1.0
tifffile==2021.6.14
tornado==6.1
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1621890532941/work
traitlets==5.0.5
typing-extensions==3.7.4.3
uritemplate==3.0.1
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1622056799390/work
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.0.1
Werkzeug==2.0.1
widgetsnbextension==3.5.1
witwidget==1.8.0
wrapt==1.12.1
xgboost==1.4.2

**Comment by jameswex** [comment]
Is there a way to downgrade to JupyterLab 2.x and try the instructions in that other bug?

**Comment by mkhaas** [comment]
Greetings @jameswex ,  I am able to resolve the issue by building a jupyter notebook image and installing the witwidget and that works and unblocks me.  Thank you for the pointers.  I am unable to spend time on JuypterLab downgrade instructions immediately. but will add findings to #164  after my attempt next week.
