### ISSUE TITLE
Can the dashboard be changed according to our need?

### ISSUE THREAD

**Issue by survivebycoding** [PAIR-code/what-if-tool#212]
Are there any APIs to change the dashboard, add new segments in the dashboard under data point, or adding new graphs, any API to do the same?

**Comment by jameswex** [comment]
The What-If Tool is static in its display. For a dynamic tool, try out LIT which is like a super-charged What-If Tool with more configurability. https://pair-code.github.io/lit/ https://github.com/pair-code/lit
