### ISSUE TITLE
what if tool for ranking model?

### ISSUE THREAD

**Issue by zabir-nabil** [PAIR-code/what-if-tool#214]
"What if tool" is really intuitive for regular classification or regression problems, loving it so far.

I want to know if it can be used for a ranking problem too. I will try to explain the problem as simply as possible.

So, let's say it's a book recommendation/ranking model, that has been trained on both book and user features.

training data -> feature set:
featueres: [book_lenght, book_category, user_age, user_gender, user_preferred_genre] label: is_relevant / is_match (0 or 1)

on the inference side, the model predicts a soft score, and based on the score the books are ranked. But the explainability should consider the fact that these predictions are grouped by the query.
Is it possible to explain the features and predictions of such a problem using "what if"?

**Comment by jameswex** [comment]
The what-if tool only has capabilities for classification and regression models, not ranking models, so it won't be of help here.

You could look into our new tool LIT which is more of a what-if tool that works for any model modality and allows the user to create their own custom calculations/metrics in python and their own front-end modules in typescript.

https://pair-code.github.io/lit/
