### ISSUE TITLE
Custom Sprite Thumbnail Dimensions

### ISSUE THREAD

**Issue by LucasVandroux** [PAIR-code/what-if-tool#222]
I had a look to understand how the sprite atlas was generated, and it seems it is not possible to modify the size of the thumbnails used:
https://github.com/PAIR-code/what-if-tool/blob/3be0f74a02843e06d747a60823e50b4295019f6a/utils/inference_utils.py#L764

When working with bigger images, this would be helpful to have larger images where we can see the differences between them, and also work with none-square images.

**Comment by jameswex** [comment]
The only way to see large images is by clicking an example to see it in the datapoint editor. We don't have plans to update the What-If Tool at this time, but do check out our follow-on tool, LIT (https://pair-code.github.io/lit/) which is much more customizable and also supports image models.
