### ISSUE TITLE
what's the difference between this and tensorboard/plugins/interactive_inference

### ISSUE THREAD

**Issue by mengban** [PAIR-code/what-if-tool#32]
I have read the two repo code, but I found that they are not exactly the same, so what's the difference between them. Like which one will updated frequently and whick one will have a newer version and etc...

**Comment by jameswex** [comment]
We're in the process of moving the code over to this repo from TensorBoard. This repo is now the source of truth of the What-If Tool. The code in TensorBoard will continue to live there for some number of weeks/months while we fully convert TensorBoard's use of WIT (as a TensorBoard dashboard) over to using the code from this repo as a dynamic plugin.

But all future pip releases of WitWidget will come from this code base and the code in TensorBoard will no longer be updated.

We'll broadly announce it soon :)
