### ISSUE TITLE
WIT missing functionality with TFX exports

### ISSUE THREAD

**Issue by drcat101** [PAIR-code/what-if-tool#54]
Similar to issue #37 I would like to use the WIT with a TFX pipeline. I am trying this out with the Iris/Native Keras example from TFX (https://github.com/tensorflow/tfx/blob/master/tfx/examples/iris/iris_pipeline_native_keras.py). I have tried both set_custom_predict_fn and set_estimator_and_feature_spec. Both allow me to load the WIT but the Predict button cannot be used. In the set_custom_predict_fn case, the WIT gives me the error "AttributeError("'list' object has no attribute 'SerializeToString'",)". In the set_estimator_and_feature_spec case, the WIT gives me the error "AttributeError("'str' object has no attribute 'predict'",)".

Here's the code in a Colab: https://colab.research.google.com/drive/1tfUZ4MLT2Ynj8LNeghOUnL7iBstEQTgv

Which is the correct way to use the WitConfigBuilder with a TFX model, and how do I correct the error?

Thanks!

**Comment by jameswex** [comment]
Thanks for reaching out. Updates to get WIT in that notebook to work:

1) Change prediction function as it takes in an array of examples, not a single example. Also extract the list of class scores from the returned dict and return it.
def predict(examples):
  preds = model.signatures['serving_default'](examples=tf.constant([example.SerializeToString() for example in examples]))
  return preds['outputs'].numpy()

2) Set up WitConfigBuilder to indicate this is a multi-class model:
config_builder = WitConfigBuilder(eval_examples).set_custom_predict_fn(predict).set_multi_class(True)

Let me know if this works as expected for you.

**Comment by drcat101** [comment]
Thank you! That works as expected.
