### ISSUE TITLE
Web demos fail to load in Safari or Firefox

### ISSUE THREAD

**Issue by kevinrobinson** [PAIR-code/what-if-tool#7]
Thanks for sharing this awesome work! 👍 

This is what folks see:
<img width="1149" alt="Screen Shot 2019-04-26 at 4 55 12 PM" src="https://user-images.githubusercontent.com/1056957/56836100-26d3f280-6844-11e9-866d-0ec27a730ad5.png">

This is what the console outputs:
<img width="883" alt="Screen Shot 2019-04-26 at 4 55 23 PM" src="https://user-images.githubusercontent.com/1056957/56836102-29cee300-6844-11e9-9ea9-df90a9ddcda2.png">
<img width="947" alt="Screen Shot 2019-04-26 at 4 55 03 PM" src="https://user-images.githubusercontent.com/1056957/56836108-2cc9d380-6844-11e9-9478-5a711cacfbf4.png">

So I'm guessing something about the Bazel config, and that it needs to include a polyfill or some other way to load Polymer code.  From poking around a bit I think it's in the config of this build command (to use the smiling dataset as an example): https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/interactive_inference/tf_interactive_inference_dashboard/demo/BUILD#L69

From searching around, I didn't find much info building polymer code with bazel outside the googleplex.  And reading that build file, it looks like it's pulling in what I'd expect in https://github.com/tensorflow/tensorboard/blob/master/tensorboard/components/tf_imports/BUILD#L16.  And it looks like it pulls in external polymer artifacts in https://github.com/tensorflow/tensorboard/blob/d3a6cfd6eb5c0fff4a405b23c5361875adf908f0/third_party/polymer.bzl#L1379.  Those must be working right, since the facets demos work fine in other browsers, so I'm guessing it's something about the specific BUILD task within `tf_interactive_inference_dashboard/demo/` but not sure what.

Thanks! :)

**Comment by jameswex** [comment]
Thanks for reporting!

To fix this we just need to include the webcomponents polyfill on the demo pages. We've actually done this already in a forked branch in TensorBoard, where all of TensorBoard (including WIT) is updating from Polymer 1 to Polymer 2.

But if that work isn't going to be pulled into master in the short term, we could also make the change separately before the Polymer 2 switchover as well. I'll look into that.

**Comment by kevinrobinson** [comment]
Congrats on the 1.3 release! 👍 FWIW, clicking through an email notice I got an empty screen trying to look at web demos in Firefox, and demos like https://pair-code.github.io/what-if-tool/image.html don't appear to work in Safari still either.

Thanks for your awesome work and design rationale at https://arxiv.org/abs/1907.04135 as well!

**Comment by jameswex** [comment]
Thanks for the heads-up, and my bad for not testing across browsers before the 1.3 release.

Perhaps we need these demos to do the same thing as the facets website demos, to work across browsers:

**Comment by kevinrobinson** [comment]
@jameswex Thanks!  This is super helpful for working around, and noted in https://github.com/PAIR-code/facets/issues/132.  And updating these WIT demos to work across browsers sounds great!

**Comment by jameswex** [comment]
This should no longer be an issue.
