### ISSUE TITLE
Jupyter Lab 2.x support

### ISSUE THREAD

**Issue by ilango100** [PAIR-code/what-if-tool#71]
The witwidget does not seem to work in Jupyter Lab 2.x versions. Even before running witWidget, I get the error:
![2020-04-16-140310_1919x217_scrot](https://user-images.githubusercontent.com/16995641/79435548-711e2880-7fed-11ea-9189-15b20aa581e3.png)

Whenever I use witwidget with Jupyter Lab 2.x, I get the error:
![2020-04-16-142201_1907x196_scrot](https://user-images.githubusercontent.com/16995641/79435786-b6425a80-7fed-11ea-941c-1eb7213ac208.png)

But when I use Jupyterlab 1.x, everything works fine. I guess the witwidget is not ported to Jupyterlab 2.x. Jupyterlab docs contain [extension migration guide](https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html), which may help in updating the widget to JupyterLab 2.x.

**Comment by jameswex** [comment]
Thanks for bringing this to our attention. You are correct that we haven't looked into updating WitWidget for Jupyter Lab 2.x yet. But we will use this bug to track that work.

**Comment by jameswex** [comment]
witwidget v1.8.0 was just released with support for jupyterlab 2.x
