### ISSUE TITLE
FP/FN Typo in ProPublica Notebook Demo

### ISSUE THREAD

**Issue by rohitmujumdar** [PAIR-code/what-if-tool#74]
In the notebook https://colab.research.google.com/github/pair-code/what-if-tool/blob/master/WIT_COMPAS.ipynb#scrollTo=VZ-rK11X5arK

The 8th cell mentions: 
"But, the FP rate is MUCH higher for African Americans and the FN rate is MUCH lower for caucasians"

Even though the data shows : 

AA FN: 15.4%
Caucasion FN: 25.2% 
AA FP: 19.5%
Caucasion FP: 9.7%

Is this a typo or are we missing something here?

**Comment by jameswex** [comment]
Good catch. Fixed by #73
