### ISSUE TITLE
Calculate/display AUC for PR curve

### ISSUE THREAD

**Issue by jameswex** [PAIR-code/what-if-tool#78]
For classification models, we display a PR curve in the performance tab. We should calculate the area under this curve and display it above the curve, in the title for the chart.

**Comment by liabifano** [comment]
Hello @jameswex can I take this issue?
Should we add the area under the curve of the ROC curve or PR curve?

**Comment by jameswex** [comment]
Thanks for reaching out! We actually did this update, I have to close this issue out. Sorry! 

You can see it in https://pair-code.github.io/what-if-tool/demos/uci.html if you go to the Performance and Fairness tab.
