### ISSUE TITLE
Smile detection demo and CelebA datapoint IDs

### ISSUE THREAD

**Issue by kevinrobinson** [PAIR-code/what-if-tool#8]
This is an awesome demo!  I spent some time exploring the performance & fairness tabs, and then digging into facets dive, and individual examples.  It's really interesting, thanks for putting together such an accessible demo 👍 

In the process I found a bunch of data points that were labeled differently than I would have expected.    I figured this was errors from the labeling that were part of the CelebA set, but it came up enough times that it led to me investigate further and try to see how many data points appeared to be mislabeled, when compared to my own personal oracle-like labeling truth :)

To debug, I downloaded the CelebA dataset and then started looking at individual data points, assuming the `Datapoint ID` in WIT would correspond to the image ID and filename in CelebA.  This doesn't seem to be the case though, and so I can't figure out how to verify further.

You can pick any number as an example (Datapoint ID 1 is what I started with when trying to compare to CelebA).  But for one full example, in facets within WIT, I noticed a datapoint was labeled "Sideburns" in a way I didn't expect looking at the image myself, so I clicked in to see the image and the datapoint ID:
![image](https://user-images.githubusercontent.com/1056957/56837473-859b6b00-6848-11e9-9b3e-a5b7fde84a4c.png)

But then checking in the the CelebA set, this is what I see for image `000038.jpg`:
![image](https://user-images.githubusercontent.com/1056957/56837490-90560000-6848-11e9-910c-c75fdc5e2a62.png)

The data in CelebA for 38 in the `list_attr_celeba.csv` file is also different than the data in WIT for Datapoint ID 38:
<img width="500" alt="Screen Shot 2019-04-26 at 5 29 02 PM" src="https://user-images.githubusercontent.com/1056957/56837547-d7dc8c00-6848-11e9-8156-e2087dffdc89.png">

Since there's only 250 examples in the WIT tool, I'm wondering if the full dataset is being sampled for the demo, and then the Datapoint ID values are being mapped to 0-249 and the reference back to the original dataset is lost?  That's just a guess though.  I see there's a bunch of data in https://github.com/PAIR-code/what-if-tool/tree/master/data/images but not sure how to debug further.

Thanks for sharing this work!

**Comment by tolga-b** [comment]
Hi Kevin, thank you for bringing this to our attention. You are right, there has been some sub-sampling and I do not think that the image IDs correspond to CelebA image ids. I will analyze this further for the web demo and give you an update! Meanwhile, you may want to check out the colab demo here https://colab.research.google.com/github/PAIR-code/what-if-tool/blob/master/WIT_Smile_Detector.ipynb.

**Comment by kevinrobinson** [comment]
@tolga-b no problem! thanks for sharing this awesome work and helping debug and understand 👍 

fwiw, what I see in https://colab.research.google.com/github/PAIR-code/what-if-tool/blob/master/WIT_Smile_Detector.ipynb#scrollTo=UwiWGrLlSWGh is that Datapoint ID 38 is another image that also does not match CelebA:
![image](https://user-images.githubusercontent.com/1056957/56838760-4a4f6b00-684d-11e9-80ff-97c00364bfd2.png)

You can see that `examples` gets sliced based on what you put in the form:
<img width="1002" alt="Screen Shot 2019-04-26 at 6 03 08 PM" src="https://user-images.githubusercontent.com/1056957/56838817-94d0e780-684d-11e9-9821-90a9dbab454f.png">

So I assume that means the full set is getting sampled and the index lost earlier on in the notebook, but didn't look more there, since the web demo is what I'm working with more directly.

Thanks for your help!

**Comment by tolga-b** [comment]
Hi Kevin,
I created a gist here to find CelebA image id from WIT image id by matching patterns: https://gist.github.com/tolga-b/5fbcab21223d9dd075e2667f86c2c9e9
The CelebA id for data point 38 is 004789.jpg. I verified that WIT demo loads the annotations correctly for this image. In future, we may include original image id as one of the fields to WIT input to make tracing back easier. Please let me know if it worked for you and thanks for detailed feedback!

**Comment by kevinrobinson** [comment]
@tolga-b Thanks! 😄 

Yeah if I download the CelebA dataset from https://www.kaggle.com/jessicali9530/celeba-dataset#list_attr_celeba.csv or from http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html, and look at the row with `image_id=004789.jpg` it looks to me like this has a `1` value.  The Kaggle page says that:

<img width="295" alt="Screen Shot 2019-07-23 at 1 17 06 PM" src="https://user-images.githubusercontent.com/1056957/61732703-33d18680-ad4c-11e9-95b3-66be8730abef.png">

So I guess to my eyes this looks like an upstream labeling bug in CelebA.  I agree it would be helpful if the image filename or CelebA `image_id` were included in any demos using that data set, but I don't have any real need for that on my end right now, so I'll close this.  Thanks for sharing the script and your work! 👍
